### ISSUE TITLE
Network SMB

### ISSUE THREAD

**Issue by GitInHereBoi** [liuw086/SuperScreen#44]
I have a suggestion for access to the Network storage through SMB. It will ask for username and password before granted access to the storage. There has to be an option to save username and password so we don't have to input it again every time we open the app.

**Comment by liuw086** [comment]
Thank you for your suggestion. I don’t provide the option to save now because by default the username and password will be saved as long as the login is successful. Next time you will log in directly, unless the password is modified, it will pop up again to ask for login authorization. I feel this reduces asynchronous operations

**Comment by GitInHereBoi** [comment]
I understand but when I exit the app by press the "B" button twice and then back in, it asked for login credential again. Just something to take care of this

**Comment by liuw086** [comment]
Thank you for your feedback. I will try to reproduce this problem. It would be great if you could provide a video of this process.

**Comment by GitInHereBoi** [comment]
Okay. I will upload a video soon

**Comment by GitInHereBoi** [comment]
I checked and it did saved my username and password to the app. Weird it didn't after I restarted. It is fine for now. Thanks. Sorry to bother you.

**Comment by liuw086** [comment]
It doesn't matter, my test equipment here is limited. Different systems and equipment may cause unexpected problems. Welcome to submit any questions and suggestions to me. Thank you.
